### ISSUE TITLE
Bug: Student cancelled from course still appears in course information page

### ISSUE THREAD

**Issue by ricky9667** [NEO-TAT/tat_flutter#121]
**Describe the bug**
In some cases, student cancel from course but still shows in the students list in course information.

**To Reproduce**
1. Go to course calendar page of student with id `108820008`
2. Click on "Compilers" course, or 「編譯器原理」in Mandarin
3. Scroll down to student with id `108820016`
4. Click the "Search" or 「搜尋」button of this student
5. You will see the "Compilers" course is actually not showing in course calendar page of this student, which may be the error

**Expected behavior**
Students that cancelled should not appear in the students list of course information page, taking the above case as example, student with id `108820016` **should not ** be shown in students list in "Compilers" information page.

**Screenshots**
![photo_2022-05-28 01 02 47](https://user-images.githubusercontent.com/55730003/170747619-1e28fff2-ff12-4200-b17c-aeea80f1a812.jpeg)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 12
 - Version 1.4 or above

**Additional context**
This is actually not an urgent issue, the priority of this task can be adjusted according to developers' concerns.

**Comment by Xanonymous-GitHub** [comment]
This seems caused by BE API, which means we will always get the wrong data.
